changelog:
  categories:
    - title: Breaking changes
      labels: [breaking]
    - title: Features
      labels: [feature, enhancement]
    - title: Fixes
      labels: [fix, bug]
    - title: Dependencies
      labels: [dependencies]
    - title: Documentation
      labels: [documentation, docs]
    - title: Other changes
      labels: ['*']
