// Generated by `bun run catalog:sync` from registry/registry.json and catalog/community-registries.json.
import type { RegistryItem } from './workspace.types'

export const catalog: readonly RegistryItem[] = [
  {
    "ref": "forms",
    "name": "forms",
    "title": "Payload forms",
    "description": "Native Payload forms, persisted submissions, a React example and console notifications.",
    "kind": "feature",
    "source": "payload-toolkit",
    "guide": "docs/payload-toolkit/forms/GUIDE.md"
  },
  {
    "ref": "@payload-components/hero-basic",
    "name": "hero-basic",
    "title": "Hero Basic",
    "description": "Payload Components proof-of-concept hero block.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/hero-split",
    "name": "hero-split",
    "title": "Hero Split",
    "description": "Two-column Payload hero block with an editor-placed visual.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/hero-video",
    "name": "hero-video",
    "title": "Hero Video",
    "description": "Full-bleed video hero with editor-managed media and a reduced-motion poster fallback.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/hero-product-tilt",
    "name": "hero-product-tilt",
    "title": "Hero Product Tilt",
    "description": "Centered product hero with a static perspective frame and editor-managed media.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/hero-aurora",
    "name": "hero-aurora",
    "title": "Hero Aurora",
    "description": "Motion-first product hero with an animated aurora field, staggered reveal, parallax panel, and metric ticker.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/hero-kinetic",
    "name": "hero-kinetic",
    "title": "Hero Kinetic",
    "description": "Motion-first editorial hero with a line-masked type reveal, cinematic plate, and velocity marquee.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/feature-grid-basic",
    "name": "feature-grid-basic",
    "title": "Feature Grid Basic",
    "description": "Text-first Payload feature grid with optional CTA wiring.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/feature-split",
    "name": "feature-split",
    "title": "Feature Split",
    "description": "Two-column Payload feature block: heading and CTA beside a feature list.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/feature-bento",
    "name": "feature-bento",
    "title": "Feature Bento",
    "description": "Asymmetric Payload bento grid with a featured lead cell and supporting cells.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/feature-steps",
    "name": "feature-steps",
    "title": "Feature Steps",
    "description": "Numbered Payload steps block for sequential, how-it-works feature flows.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/feature-accordion",
    "name": "feature-accordion",
    "title": "Feature Accordion",
    "description": "Synchronized feature accordion with editor-selected icons and optional media.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/feature-cards-media",
    "name": "feature-cards-media",
    "title": "Feature Cards Media",
    "description": "Two-column feature cards with independent media and optional icons.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/feature-icon-grid",
    "name": "feature-icon-grid",
    "title": "Feature Icon Grid",
    "description": "Dense feature grid with editor-selected icons and a tokenized radial decorator.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/embed-basic",
    "name": "embed-basic",
    "title": "Embed Basic",
    "description": "Responsive, accessible sandboxed iframe block for approved HTTPS embeds.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/logo-cloud-grid",
    "name": "logo-cloud-grid",
    "title": "Logo Cloud Grid",
    "description": "Centered, wrapping wall of editable logo uploads under a heading.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/logo-cloud-hover",
    "name": "logo-cloud-hover",
    "title": "Logo Cloud Hover",
    "description": "Logo wall that dims and blurs on hover to reveal a CTA link.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/logo-cloud-marquee",
    "name": "logo-cloud-marquee",
    "title": "Logo Cloud Marquee",
    "description": "Auto-scrolling marquee of editable logos with progressive-blur edge fades.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/logo-cloud-inline",
    "name": "logo-cloud-inline",
    "title": "Logo Cloud Inline",
    "description": "Compact label-over-logos strip of editable trust logos.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/logo-cloud-inline-wrap",
    "name": "logo-cloud-inline-wrap",
    "title": "Logo Cloud Inline Wrap",
    "description": "Single wrapping row keeping the label inline with editable logos.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/content-columns",
    "name": "content-columns",
    "title": "Content Columns",
    "description": "Two-column Payload content block: a heading beside body copy and a CTA.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/content-image-lead",
    "name": "content-image-lead",
    "title": "Content Image Lead",
    "description": "Payload content block led by a full-width image above a heading, body, and CTA.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/content-feature-media",
    "name": "content-feature-media",
    "title": "Content Feature Media",
    "description": "Payload content block: body copy and two icon features beside a framed media panel.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/content-feature-split",
    "name": "content-feature-split",
    "title": "Content Feature Split",
    "description": "Payload content block: a side media panel beside body copy and two icon features.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/content-showcase",
    "name": "content-showcase",
    "title": "Content Showcase",
    "description": "Payload content block: a centered intro, a full-width image, and a four-up feature grid.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/content-quote",
    "name": "content-quote",
    "title": "Content Quote",
    "description": "Payload content block: a media panel beside body copy and a cited pull quote.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/content-community",
    "name": "content-community",
    "title": "Content Community",
    "description": "Payload content block: a centered heading and body above a wall of community avatars.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/integration-grid",
    "name": "integration-grid",
    "title": "Integration Grid",
    "description": "A responsive grid of integration cards with logo, name, description, and a learn-more link.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/integration-cluster",
    "name": "integration-cluster",
    "title": "Integration Cluster",
    "description": "A centered cluster of integration logos around a featured brand mark, with a heading and CTA.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/integration-split",
    "name": "integration-split",
    "title": "Integration Split",
    "description": "A two-column section pairing a featured-mark logo cluster with a heading, subtext, and CTA.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/integration-connect",
    "name": "integration-connect",
    "title": "Integration Connect",
    "description": "Integration logos wired to a central brand mark by connector lines.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/integration-orbit",
    "name": "integration-orbit",
    "title": "Integration Orbit",
    "description": "Concentric rings of integration logos that orbit a featured brand mark on hover.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/integration-list",
    "name": "integration-list",
    "title": "Integration List",
    "description": "A vertical list of integration rows with logo, name, description, and an add action.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/integration-marquee",
    "name": "integration-marquee",
    "title": "Integration Marquee",
    "description": "Three auto-scrolling rows of integration logos around a featured brand mark.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/integration-testimonial",
    "name": "integration-testimonial",
    "title": "Integration Testimonial",
    "description": "A two-column section pairing a customer quote with a grid of integration logo cards.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/content-split-rows",
    "name": "content-split-rows",
    "title": "Content Split Rows",
    "description": "Payload content block: an intro above alternating media-and-text rows.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/content-rows",
    "name": "content-rows",
    "title": "Content Rows",
    "description": "Payload content block: an intro above a uniform stack of media-and-text rows.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/content-image-frame",
    "name": "content-image-frame",
    "title": "Content Image Frame",
    "description": "Payload content block: a centered intro above a layered, framed screenshot.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/content-stats",
    "name": "content-stats",
    "title": "Content Stats",
    "description": "Payload content block: an intro, a grid of icon features, and a stats list.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/content-list",
    "name": "content-list",
    "title": "Content List",
    "description": "Payload content block: a serif heading beside a labeled-term list.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/content-list-columns",
    "name": "content-list-columns",
    "title": "Content List Columns",
    "description": "Payload content block: a serif heading above a two-column labeled-term list.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/content-list-icons",
    "name": "content-list-icons",
    "title": "Content List Icons",
    "description": "Payload content block: a serif heading and intro above a multi-column icon list.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/call-to-action-centered",
    "name": "call-to-action-centered",
    "title": "Call To Action Centered",
    "description": "Centered Payload call-to-action block: heading, copy, and one or two CTA links.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/call-to-action-boxed",
    "name": "call-to-action-boxed",
    "title": "Call To Action Boxed",
    "description": "Boxed Payload call-to-action block: heading, copy, and CTA links inside a nested panel.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/call-to-action-split",
    "name": "call-to-action-split",
    "title": "Call To Action Split",
    "description": "Split Payload call-to-action block: heading and copy on one side, CTA links and assurance on the other.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/call-to-action-signup",
    "name": "call-to-action-signup",
    "title": "Call To Action Signup",
    "description": "Email-capture Payload call-to-action block: heading, copy, and a form that posts to a same-origin endpoint.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/contact-routing-form",
    "name": "contact-routing-form",
    "title": "Contact Routing Form",
    "description": "Validated contact channels beside an accessible same-origin inquiry form.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/contact-channels",
    "name": "contact-channels",
    "title": "Contact Channels",
    "description": "Form-free Payload contact block: a grid of validated email, phone, and URL channels.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/team-roster",
    "name": "team-roster",
    "title": "Team Roster",
    "description": "Payload team block: department-grouped sections, each a grid of member avatars with name and role.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/team-grid",
    "name": "team-grid",
    "title": "Team Grid",
    "description": "Payload team block: a heading and intro above a responsive grid of member photo cards that reveal role on hover.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/team-bios",
    "name": "team-bios",
    "title": "Team Bios",
    "description": "Bio-forward Payload team block: two-up member cards with avatar, role, and biography.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/faq-accordion",
    "name": "faq-accordion",
    "title": "FAQ Accordion",
    "description": "Payload FAQ block: a centered accordion of question/answer items with an optional CTA.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/faq-split",
    "name": "faq-split",
    "title": "FAQ Split",
    "description": "Payload FAQ block: a two-column layout pairing a sticky heading and CTA with an accordion.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/faq-card",
    "name": "faq-card",
    "title": "FAQ Card",
    "description": "Payload FAQ block: a centered accordion wrapped in a card with an optional CTA.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/faq-icons",
    "name": "faq-icons",
    "title": "FAQ Icons",
    "description": "Payload FAQ block: an accordion with a per-question icon from a fixed allowlist.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/faq-grouped",
    "name": "faq-grouped",
    "title": "FAQ Grouped",
    "description": "Payload FAQ block: titled, icon-tagged category groups of accordions.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/faq-grid",
    "name": "faq-grid",
    "title": "FAQ Grid",
    "description": "Payload FAQ block: a static two-column grid of question/answer cards.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/comparator-table",
    "name": "comparator-table",
    "title": "Comparator Table",
    "description": "Tiered feature-comparison table Payload block: plan columns with CTAs over grouped feature rows.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/comparator-grid",
    "name": "comparator-grid",
    "title": "Comparator Grid",
    "description": "Plan-column comparison Payload block: pricing columns in a bordered card over a feature matrix.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/comparator-stack",
    "name": "comparator-stack",
    "title": "Comparator Stack",
    "description": "Stacked plan-card comparison Payload block: one card per plan with its own price, CTA, and feature checklist.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/testimonials-quote",
    "name": "testimonials-quote",
    "title": "Testimonials Quote",
    "description": "Payload testimonials block: a single featured quote with a left accent bar, author, optional role, and avatar.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/testimonials-spotlight",
    "name": "testimonials-spotlight",
    "title": "Testimonials Spotlight",
    "description": "Payload testimonials block: a single centered testimonial with a quote-mark, large avatar, author, and role.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/testimonials-grid",
    "name": "testimonials-grid",
    "title": "Testimonials Grid",
    "description": "Payload testimonials block: a heading above a responsive grid of quote cards, each with author, optional role, and avatar.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/testimonials-rating",
    "name": "testimonials-rating",
    "title": "Testimonials Rating",
    "description": "Payload testimonials block: a responsive grid of review cards, each with a star rating, quote, author, optional role, and avatar.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/testimonials-bento",
    "name": "testimonials-bento",
    "title": "Testimonials Bento",
    "description": "Payload testimonials block: an asymmetric bento with one featured quote in a large cell and supporting quotes around it.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/testimonials-wall",
    "name": "testimonials-wall",
    "title": "Testimonials Wall",
    "description": "Payload testimonials block: a heading above a multi-column masonry wall of compact testimonial cards.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/stats-proof",
    "name": "stats-proof",
    "title": "Stats Proof",
    "description": "Narrative and prominent string metrics paired with semantic customer proof.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/stats-grid",
    "name": "stats-grid",
    "title": "Stats Grid",
    "description": "Heading and intro above a responsive grid of large string metrics on rule-topped columns.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/stats-card",
    "name": "stats-card",
    "title": "Stats Card",
    "description": "A centred heading above one divided panel that splits metrics into equal columns.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/stats-inline",
    "name": "stats-inline",
    "title": "Stats Inline",
    "description": "Heading and intro above rule-topped rows where each figure reads as one sentence.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/pricing-cards",
    "name": "pricing-cards",
    "title": "Pricing Cards",
    "description": "Three-up pricing table of editable plan cards with a highlighted plan.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/pricing-cards-muted",
    "name": "pricing-cards-muted",
    "title": "Pricing Cards Muted",
    "description": "Three-up pricing table on muted card surfaces with a highlighted plan.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/pricing-cards-cta",
    "name": "pricing-cards-cta",
    "title": "Pricing Cards CTA",
    "description": "Three-up pricing table with the CTA inside each plan header.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/pricing-split",
    "name": "pricing-split",
    "title": "Pricing Split",
    "description": "Two-plan split pricing: a compact entry plan beside an expanded featured plan.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/pricing-enterprise",
    "name": "pricing-enterprise",
    "title": "Pricing Enterprise",
    "description": "Single wide enterprise pricing panel with an editable trust-logo wall.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/collection-query",
    "name": "collection-query",
    "title": "Collection Query",
    "description": "A Pages block that queries the starter Posts collection by category or manual selection and renders grid, list, or featured cards.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/footer-columns",
    "name": "footer-columns",
    "title": "Footer Columns",
    "description": "A brand block beside labelled columns of navigation links, closed by a copyright rule.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/footer-simple",
    "name": "footer-simple",
    "title": "Footer Simple",
    "description": "A compact footer keeping the brand and one wrapped row of links on a line, copyright beneath.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/footer-centered",
    "name": "footer-centered",
    "title": "Footer Centered",
    "description": "A centred brand, tagline, and navigation above a rule carrying copyright and policy links.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/contact-form-basic",
    "name": "contact-form-basic",
    "title": "Contact Form Basic",
    "description": "An accessible contact form with name, email, organization, and message fields, inline validation, and confirmed submission feedback.",
    "kind": "block",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/post-hero",
    "name": "post-hero",
    "title": "Post Hero",
    "description": "An editorial article header with title, summary, categories, byline, date, and an optional image slot.",
    "kind": "component",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/author-card",
    "name": "author-card",
    "title": "Author Card",
    "description": "An article author profile with optional avatar, role, biography, and profile link.",
    "kind": "component",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/newsletter-callout",
    "name": "newsletter-callout",
    "title": "Newsletter Callout",
    "description": "A newsletter signup callout with a consumer-owned form endpoint.",
    "kind": "component",
    "source": "@payload-components"
  },
  {
    "ref": "@payload-components/related-posts",
    "name": "related-posts",
    "title": "Related Posts",
    "description": "A compact end-of-post list of related articles your template selects; the current post is always excluded.",
    "kind": "component",
    "source": "@payload-components"
  }
]
