// Generated by `bun run catalog:sync` from registry/registry.json, catalog/community-registries.json and public/registry-previews/manifest.json.
import type { RegistryItem } from './workspace.types'

export const catalog: readonly RegistryItem[] = [
  {
    "ref": "forms",
    "name": "forms",
    "title": "Payload forms",
    "description": "Native Payload forms, persisted submissions, a React example and console notifications.",
    "kind": "feature",
    "source": "payload-toolkit",
    "guide": "docs/payload-toolkit/forms/GUIDE.md"
  },
  {
    "ref": "@payload-components/hero-basic",
    "name": "hero-basic",
    "title": "Hero Basic",
    "description": "Payload Components proof-of-concept hero block.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/hero-basic",
    "image": "/registry-previews/53e7f523f4dd818f890b4a5b3375edb2ec4d6924a66213ee1d5aa4142609f14f.png"
  },
  {
    "ref": "@payload-components/hero-split",
    "name": "hero-split",
    "title": "Hero Split",
    "description": "Two-column Payload hero block with an editor-placed visual.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/hero-split",
    "image": "/registry-previews/1ec18fdc1d40295addc02e8e2f29ef42be343ff0f5f9b8d8d4fe1983fb330db6.png"
  },
  {
    "ref": "@payload-components/hero-video",
    "name": "hero-video",
    "title": "Hero Video",
    "description": "Full-bleed video hero with editor-managed media and a reduced-motion poster fallback.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/hero-video",
    "image": "/registry-previews/5e24aadf94a74124574f8429123f479c3f98bfd1f74763998ea9f18516cf9875.png"
  },
  {
    "ref": "@payload-components/hero-product-tilt",
    "name": "hero-product-tilt",
    "title": "Hero Product Tilt",
    "description": "Centered product hero with a static perspective frame and editor-managed media.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/hero-product-tilt",
    "image": "/registry-previews/98a073c3a9df87df5c62463189e40136f9e716b098d79455005c3fbc60dcd183.png"
  },
  {
    "ref": "@payload-components/hero-aurora",
    "name": "hero-aurora",
    "title": "Hero Aurora",
    "description": "Motion-first product hero with an animated aurora field, staggered reveal, parallax panel, and metric ticker.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/hero-aurora",
    "image": "/registry-previews/cc2c57e3ed617e69bfa3795e5703e3f6139bfa151ecb8256b91b7f1f4d0c9295.png"
  },
  {
    "ref": "@payload-components/hero-kinetic",
    "name": "hero-kinetic",
    "title": "Hero Kinetic",
    "description": "Motion-first editorial hero with a line-masked type reveal, cinematic plate, and velocity marquee.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/hero-kinetic",
    "image": "/registry-previews/600d9c85883eddc996d1c629b0bffce70d9c210747018382bb834099f7df3f68.png"
  },
  {
    "ref": "@payload-components/feature-grid-basic",
    "name": "feature-grid-basic",
    "title": "Feature Grid Basic",
    "description": "Text-first Payload feature grid with optional CTA wiring.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/feature-grid-basic",
    "image": "/registry-previews/c54dee2f6ec5a41ff5ff34cf63403deb593d663028c6fd8171894a67c5f094e8.png"
  },
  {
    "ref": "@payload-components/feature-split",
    "name": "feature-split",
    "title": "Feature Split",
    "description": "Two-column Payload feature block: heading and CTA beside a feature list.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/feature-split",
    "image": "/registry-previews/ba96b7134404490a84e7f05531bdfe56be1f44cffff312da4ad36a3cd0e4d722.png"
  },
  {
    "ref": "@payload-components/feature-bento",
    "name": "feature-bento",
    "title": "Feature Bento",
    "description": "Asymmetric Payload bento grid with a featured lead cell and supporting cells.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/feature-bento",
    "image": "/registry-previews/1255925b22fdd3c5840c75dc649ba69b1d9f3b1eda71eaee11806403c4da4012.png"
  },
  {
    "ref": "@payload-components/feature-steps",
    "name": "feature-steps",
    "title": "Feature Steps",
    "description": "Numbered Payload steps block for sequential, how-it-works feature flows.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/feature-steps",
    "image": "/registry-previews/ad9cde2c00559acb3a2e53d7b2b6654ff18f3c089929207aa1ebe83279e46330.png"
  },
  {
    "ref": "@payload-components/feature-accordion",
    "name": "feature-accordion",
    "title": "Feature Accordion",
    "description": "Synchronized feature accordion with editor-selected icons and optional media.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/feature-accordion",
    "image": "/registry-previews/659a0701d0ce9ad41f519a897a3ec6c0e39c22597270f24f7eb0a1a68028c555.png"
  },
  {
    "ref": "@payload-components/feature-cards-media",
    "name": "feature-cards-media",
    "title": "Feature Cards Media",
    "description": "Two-column feature cards with independent media and optional icons.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/feature-cards-media",
    "image": "/registry-previews/2b5c8619340bc38d9a8a4516f8e9b88d478a6a3b06aa200fc9f652a206fbbd4a.png"
  },
  {
    "ref": "@payload-components/feature-icon-grid",
    "name": "feature-icon-grid",
    "title": "Feature Icon Grid",
    "description": "Dense feature grid with editor-selected icons and a tokenized radial decorator.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/feature-icon-grid",
    "image": "/registry-previews/84c2a20bc0b5ba57c833e2222bd6686eb1b9d7883e1fa854b5f83ea944dfc031.png"
  },
  {
    "ref": "@payload-components/embed-basic",
    "name": "embed-basic",
    "title": "Embed Basic",
    "description": "Responsive, accessible sandboxed iframe block for approved HTTPS embeds.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/embed-basic",
    "image": "/registry-previews/796b431e817abcddb1b2526f701030fb426d8fa94f62b44217e8c58d5e2bddad.png"
  },
  {
    "ref": "@payload-components/logo-cloud-grid",
    "name": "logo-cloud-grid",
    "title": "Logo Cloud Grid",
    "description": "Centered, wrapping wall of editable logo uploads under a heading.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/logo-cloud-grid",
    "image": "/registry-previews/11a8c16a9f4ff9c5e624465a681dc455cc3a4d385dcb5edb1ae6fe21e4af1c4c.png"
  },
  {
    "ref": "@payload-components/logo-cloud-hover",
    "name": "logo-cloud-hover",
    "title": "Logo Cloud Hover",
    "description": "Logo wall that dims and blurs on hover to reveal a CTA link.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/logo-cloud-hover",
    "image": "/registry-previews/58d172fe8df18718c8c991b2280c366a024f2c031de1081e642e706e95d369ba.png"
  },
  {
    "ref": "@payload-components/logo-cloud-marquee",
    "name": "logo-cloud-marquee",
    "title": "Logo Cloud Marquee",
    "description": "Auto-scrolling marquee of editable logos with progressive-blur edge fades.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/logo-cloud-marquee",
    "image": "/registry-previews/1a1806c6a700b78396b08dfa8497e3168202563c4e8ee6ef05452cdb1a92a110.png"
  },
  {
    "ref": "@payload-components/logo-cloud-inline",
    "name": "logo-cloud-inline",
    "title": "Logo Cloud Inline",
    "description": "Compact label-over-logos strip of editable trust logos.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/logo-cloud-inline",
    "image": "/registry-previews/28164ed861cf57e61e5fa1eced145781a8dd33e13e072e032a0da1e979b0cd24.png"
  },
  {
    "ref": "@payload-components/logo-cloud-inline-wrap",
    "name": "logo-cloud-inline-wrap",
    "title": "Logo Cloud Inline Wrap",
    "description": "Single wrapping row keeping the label inline with editable logos.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/logo-cloud-inline-wrap",
    "image": "/registry-previews/0c33b7dbca2365d8b13cba92806ab9398cb42ac186630daa43d944b737c2c577.png"
  },
  {
    "ref": "@payload-components/content-columns",
    "name": "content-columns",
    "title": "Content Columns",
    "description": "Two-column Payload content block: a heading beside body copy and a CTA.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/content-columns",
    "image": "/registry-previews/7dc7f37a4c6f23d3b2e0add16def2f44750364a11942a9cee723bd93fabe6fd4.png"
  },
  {
    "ref": "@payload-components/content-image-lead",
    "name": "content-image-lead",
    "title": "Content Image Lead",
    "description": "Payload content block led by a full-width image above a heading, body, and CTA.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/content-image-lead",
    "image": "/registry-previews/6e592c1c977563537044af448fb86649b167a9368b02d94c5cb676f9c0f61307.png"
  },
  {
    "ref": "@payload-components/content-feature-media",
    "name": "content-feature-media",
    "title": "Content Feature Media",
    "description": "Payload content block: body copy and two icon features beside a framed media panel.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/content-feature-media",
    "image": "/registry-previews/47e44d381f24471f38a0256f27ba5c7010e98cf29c247e3c91e98e698253e537.png"
  },
  {
    "ref": "@payload-components/content-feature-split",
    "name": "content-feature-split",
    "title": "Content Feature Split",
    "description": "Payload content block: a side media panel beside body copy and two icon features.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/content-feature-split",
    "image": "/registry-previews/ab84a079d551dcb16718f64c3c1f26b052694f92eec6df87d01d43e8355af799.png"
  },
  {
    "ref": "@payload-components/content-showcase",
    "name": "content-showcase",
    "title": "Content Showcase",
    "description": "Payload content block: a centered intro, a full-width image, and a four-up feature grid.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/content-showcase",
    "image": "/registry-previews/e9e8de526ba56729a86230f8d3abea807422c062fd56ac4cb92a143062d36a67.png"
  },
  {
    "ref": "@payload-components/content-quote",
    "name": "content-quote",
    "title": "Content Quote",
    "description": "Payload content block: a media panel beside body copy and a cited pull quote.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/content-quote",
    "image": "/registry-previews/43792bd9801013484a768233b73d66e4e582bcde0abb7e3cb1e42ea13f5cca1d.png"
  },
  {
    "ref": "@payload-components/content-community",
    "name": "content-community",
    "title": "Content Community",
    "description": "Payload content block: a centered heading and body above a wall of community avatars.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/content-community",
    "image": "/registry-previews/07c291fb0304862faecc9cfcdd06981de99212958e5721d42490e124e3e119f4.png"
  },
  {
    "ref": "@payload-components/integration-grid",
    "name": "integration-grid",
    "title": "Integration Grid",
    "description": "A responsive grid of integration cards with logo, name, description, and a learn-more link.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/integration-grid",
    "image": "/registry-previews/75482c0e9e35d58a6ad34f6e7dddcf257b343d5b2170945f94a11bf73adf028d.png"
  },
  {
    "ref": "@payload-components/integration-cluster",
    "name": "integration-cluster",
    "title": "Integration Cluster",
    "description": "A centered cluster of integration logos around a featured brand mark, with a heading and CTA.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/integration-cluster",
    "image": "/registry-previews/553088f2ac5abbfb01a1fb362396174eee57178cb24ab5fe3f173577c78ff120.png"
  },
  {
    "ref": "@payload-components/integration-split",
    "name": "integration-split",
    "title": "Integration Split",
    "description": "A two-column section pairing a featured-mark logo cluster with a heading, subtext, and CTA.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/integration-split",
    "image": "/registry-previews/2a036437e4085721c9fc1c9f6acab7017aa290ea15cb7109ad5f27a52e3676db.png"
  },
  {
    "ref": "@payload-components/integration-connect",
    "name": "integration-connect",
    "title": "Integration Connect",
    "description": "Integration logos wired to a central brand mark by connector lines.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/integration-connect",
    "image": "/registry-previews/c52ed247b238a5e497cd8c6235f344f1894232d83747f81200a01ddd172aa8f7.png"
  },
  {
    "ref": "@payload-components/integration-orbit",
    "name": "integration-orbit",
    "title": "Integration Orbit",
    "description": "Concentric rings of integration logos that orbit a featured brand mark on hover.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/integration-orbit",
    "image": "/registry-previews/f97568b51951fa2c43e1e8132c23235fb7ccf8863cec942c10b97d7e6235c6a0.png"
  },
  {
    "ref": "@payload-components/integration-list",
    "name": "integration-list",
    "title": "Integration List",
    "description": "A vertical list of integration rows with logo, name, description, and an add action.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/integration-list",
    "image": "/registry-previews/14d55ea9159747fdfa8397706d54a860932324e92ec40c649f32e9e0bbe524ea.png"
  },
  {
    "ref": "@payload-components/integration-marquee",
    "name": "integration-marquee",
    "title": "Integration Marquee",
    "description": "Three auto-scrolling rows of integration logos around a featured brand mark.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/integration-marquee",
    "image": "/registry-previews/dc63a00a98653936aeb26cd898de45c6ce68b06548377a99cc7ec435264c6bed.png"
  },
  {
    "ref": "@payload-components/integration-testimonial",
    "name": "integration-testimonial",
    "title": "Integration Testimonial",
    "description": "A two-column section pairing a customer quote with a grid of integration logo cards.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/integration-testimonial",
    "image": "/registry-previews/0fc70031617e56cd49dc4bbed6c8f5466f278a7dad66bf5742018fe3609d9485.png"
  },
  {
    "ref": "@payload-components/content-split-rows",
    "name": "content-split-rows",
    "title": "Content Split Rows",
    "description": "Payload content block: an intro above alternating media-and-text rows.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/content-split-rows",
    "image": "/registry-previews/f3dcb1f3cabeb62f70b3389a43ed1a3f34dc1b8704e214f5c3caea40707d9423.png"
  },
  {
    "ref": "@payload-components/content-rows",
    "name": "content-rows",
    "title": "Content Rows",
    "description": "Payload content block: an intro above a uniform stack of media-and-text rows.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/content-rows",
    "image": "/registry-previews/a1887c9dea48a72adc6f8671c733e288088876301ebb61372a3fb11699cff4f6.png"
  },
  {
    "ref": "@payload-components/content-image-frame",
    "name": "content-image-frame",
    "title": "Content Image Frame",
    "description": "Payload content block: a centered intro above a layered, framed screenshot.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/content-image-frame",
    "image": "/registry-previews/cd17bd1f281a6f8667f678a491020a7d1fbb97cf8c447b4ed5e9c88bcf2bc0d0.png"
  },
  {
    "ref": "@payload-components/content-stats",
    "name": "content-stats",
    "title": "Content Stats",
    "description": "Payload content block: an intro, a grid of icon features, and a stats list.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/content-stats",
    "image": "/registry-previews/e156efe209c223823c346006f223e70443bf6fff214ec998d906683099aaee6d.png"
  },
  {
    "ref": "@payload-components/content-list",
    "name": "content-list",
    "title": "Content List",
    "description": "Payload content block: a serif heading beside a labeled-term list.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/content-list",
    "image": "/registry-previews/b8ed217fb0c2c5ff47e3ac469266908e1ae21aaeb536ba1d3dd9cfbf46ee6c92.png"
  },
  {
    "ref": "@payload-components/content-list-columns",
    "name": "content-list-columns",
    "title": "Content List Columns",
    "description": "Payload content block: a serif heading above a two-column labeled-term list.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/content-list-columns",
    "image": "/registry-previews/f317c72499411075f599a139d4f8bf26a08c403222b6d201d3c6297774b6a822.png"
  },
  {
    "ref": "@payload-components/content-list-icons",
    "name": "content-list-icons",
    "title": "Content List Icons",
    "description": "Payload content block: a serif heading and intro above a multi-column icon list.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/content-list-icons",
    "image": "/registry-previews/d1e14d713fe281322f134b6a654a47839bd11055b12d777eb72061d6512cbe03.png"
  },
  {
    "ref": "@payload-components/call-to-action-centered",
    "name": "call-to-action-centered",
    "title": "Call To Action Centered",
    "description": "Centered Payload call-to-action block: heading, copy, and one or two CTA links.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/call-to-action-centered",
    "image": "/registry-previews/b2bc772dc1267f7da7d06f4723dda2846ec5fc2e1bf26f83ee17b83e16e205b3.png"
  },
  {
    "ref": "@payload-components/call-to-action-boxed",
    "name": "call-to-action-boxed",
    "title": "Call To Action Boxed",
    "description": "Boxed Payload call-to-action block: heading, copy, and CTA links inside a nested panel.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/call-to-action-boxed",
    "image": "/registry-previews/f32a1eefada8a387e74f44e0a5daec5c6a1a873934e73c4454219d7c442e1796.png"
  },
  {
    "ref": "@payload-components/call-to-action-split",
    "name": "call-to-action-split",
    "title": "Call To Action Split",
    "description": "Split Payload call-to-action block: heading and copy on one side, CTA links and assurance on the other.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/call-to-action-split",
    "image": "/registry-previews/00399a4259df7add7a472a04134dd203f174c18ef15b85bb1d6959463a993d8e.png"
  },
  {
    "ref": "@payload-components/call-to-action-signup",
    "name": "call-to-action-signup",
    "title": "Call To Action Signup",
    "description": "Email-capture Payload call-to-action block: heading, copy, and a form that posts to a same-origin endpoint.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/call-to-action-signup",
    "image": "/registry-previews/52c210c060260417d0ad8949fced38ab5654f204c19e2acf92c6e366f1997f62.png"
  },
  {
    "ref": "@payload-components/contact-routing-form",
    "name": "contact-routing-form",
    "title": "Contact Routing Form",
    "description": "Validated contact channels beside an accessible same-origin inquiry form.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/contact-routing-form",
    "image": "/registry-previews/c6c36f1febcf7efbdb5d6548b65ca3940b4fc975248d7a27e0cbd46236f970f7.png"
  },
  {
    "ref": "@payload-components/contact-channels",
    "name": "contact-channels",
    "title": "Contact Channels",
    "description": "Form-free Payload contact block: a grid of validated email, phone, and URL channels.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/contact-channels",
    "image": "/registry-previews/ecfcb52eb072c06724b8a5c4fb729e5130a9d216b5f801fe789e03febc6ce9f2.png"
  },
  {
    "ref": "@payload-components/team-roster",
    "name": "team-roster",
    "title": "Team Roster",
    "description": "Payload team block: department-grouped sections, each a grid of member avatars with name and role.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/team-roster",
    "image": "/registry-previews/da68e3a1f188be478e1fdf897b26ae05464f8f4fa40005c06353dc4f9a234f6e.png"
  },
  {
    "ref": "@payload-components/team-grid",
    "name": "team-grid",
    "title": "Team Grid",
    "description": "Payload team block: a heading and intro above a responsive grid of member photo cards that reveal role on hover.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/team-grid",
    "image": "/registry-previews/2b551978867e4bb4c06102514247d540d5b3950e747a00a18379dc7968e97495.png"
  },
  {
    "ref": "@payload-components/team-bios",
    "name": "team-bios",
    "title": "Team Bios",
    "description": "Bio-forward Payload team block: two-up member cards with avatar, role, and biography.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/team-bios",
    "image": "/registry-previews/3ed5ff4589851f95f3da66fa81b4e955ced8dd4c6583afbaceb84c1478bdb6ac.png"
  },
  {
    "ref": "@payload-components/faq-accordion",
    "name": "faq-accordion",
    "title": "FAQ Accordion",
    "description": "Payload FAQ block: a centered accordion of question/answer items with an optional CTA.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/faq-accordion",
    "image": "/registry-previews/bc9dc86af008b3ded38a884f90e27db9147be6d6204dd4273e03dc8d85d40e1b.png"
  },
  {
    "ref": "@payload-components/faq-split",
    "name": "faq-split",
    "title": "FAQ Split",
    "description": "Payload FAQ block: a two-column layout pairing a sticky heading and CTA with an accordion.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/faq-split",
    "image": "/registry-previews/8aa4ceea81126798a010e7829b54827450441354fee951c469e9f0cfc2c4bac8.png"
  },
  {
    "ref": "@payload-components/faq-card",
    "name": "faq-card",
    "title": "FAQ Card",
    "description": "Payload FAQ block: a centered accordion wrapped in a card with an optional CTA.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/faq-card",
    "image": "/registry-previews/de1af9e470b0a9040d536399ecf59db37b2a4c83e2d18d6622569e191d47b8d0.png"
  },
  {
    "ref": "@payload-components/faq-icons",
    "name": "faq-icons",
    "title": "FAQ Icons",
    "description": "Payload FAQ block: an accordion with a per-question icon from a fixed allowlist.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/faq-icons",
    "image": "/registry-previews/7adc3cee0a60d06d2c16afddb682d16136735aebe19390d4b11bb93ff59e76d0.png"
  },
  {
    "ref": "@payload-components/faq-grouped",
    "name": "faq-grouped",
    "title": "FAQ Grouped",
    "description": "Payload FAQ block: titled, icon-tagged category groups of accordions.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/faq-grouped",
    "image": "/registry-previews/39ca9e7ae10c7c6c296b1fa311d74b52b56854d7a41822dcb49e634266e4c6e4.png"
  },
  {
    "ref": "@payload-components/faq-grid",
    "name": "faq-grid",
    "title": "FAQ Grid",
    "description": "Payload FAQ block: a static two-column grid of question/answer cards.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/faq-grid",
    "image": "/registry-previews/92a2e9d9d956534bcf86ecaee55d45b31fc5d110b93853ef4538764c22ec848b.png"
  },
  {
    "ref": "@payload-components/comparator-table",
    "name": "comparator-table",
    "title": "Comparator Table",
    "description": "Tiered feature-comparison table Payload block: plan columns with CTAs over grouped feature rows.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/comparator-table",
    "image": "/registry-previews/f14f5f77361b38e167e998739379972789bb297e2ba9788266ef28562b986820.png"
  },
  {
    "ref": "@payload-components/comparator-grid",
    "name": "comparator-grid",
    "title": "Comparator Grid",
    "description": "Plan-column comparison Payload block: pricing columns in a bordered card over a feature matrix.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/comparator-grid",
    "image": "/registry-previews/430dfe9e5a1cef8cd8384b49251b92da1f2dba15bbe367762337cbf44274ef7d.png"
  },
  {
    "ref": "@payload-components/comparator-stack",
    "name": "comparator-stack",
    "title": "Comparator Stack",
    "description": "Stacked plan-card comparison Payload block: one card per plan with its own price, CTA, and feature checklist.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/comparator-stack",
    "image": "/registry-previews/bea0ec49cedacafdd132778ab1a10a134dc5ef0f95aafea15ff89971a6b5ef0a.png"
  },
  {
    "ref": "@payload-components/testimonials-quote",
    "name": "testimonials-quote",
    "title": "Testimonials Quote",
    "description": "Payload testimonials block: a single featured quote with a left accent bar, author, optional role, and avatar.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/testimonials-quote",
    "image": "/registry-previews/fe2286515963a59ba18a421d24c60f5ce1d5822df1b31ff7e066124466fddd2c.png"
  },
  {
    "ref": "@payload-components/testimonials-spotlight",
    "name": "testimonials-spotlight",
    "title": "Testimonials Spotlight",
    "description": "Payload testimonials block: a single centered testimonial with a quote-mark, large avatar, author, and role.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/testimonials-spotlight",
    "image": "/registry-previews/5e2fdcbb76b645cd32f8524541783fcb6be5ec0e5661c57b27a3cb9dadc8db26.png"
  },
  {
    "ref": "@payload-components/testimonials-grid",
    "name": "testimonials-grid",
    "title": "Testimonials Grid",
    "description": "Payload testimonials block: a heading above a responsive grid of quote cards, each with author, optional role, and avatar.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/testimonials-grid",
    "image": "/registry-previews/5d480edc22329b2729e7d9fca9f1185c5238fb3324c34966d9aaaa66b455cad8.png"
  },
  {
    "ref": "@payload-components/testimonials-rating",
    "name": "testimonials-rating",
    "title": "Testimonials Rating",
    "description": "Payload testimonials block: a responsive grid of review cards, each with a star rating, quote, author, optional role, and avatar.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/testimonials-rating",
    "image": "/registry-previews/d92dc91d1fa2d245a6df98d438154921eba524732fdae045fd8157265dc82da3.png"
  },
  {
    "ref": "@payload-components/testimonials-bento",
    "name": "testimonials-bento",
    "title": "Testimonials Bento",
    "description": "Payload testimonials block: an asymmetric bento with one featured quote in a large cell and supporting quotes around it.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/testimonials-bento",
    "image": "/registry-previews/eb5df84d09af837a695974b7d4f551f424b3d9d95c9c8d9323098174fdeac3ea.png"
  },
  {
    "ref": "@payload-components/testimonials-wall",
    "name": "testimonials-wall",
    "title": "Testimonials Wall",
    "description": "Payload testimonials block: a heading above a multi-column masonry wall of compact testimonial cards.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/testimonials-wall",
    "image": "/registry-previews/a5aba520b8ff8d17f673aabec2a28a4fbf74ef895b40b5bb2f8122bd9b4e2137.png"
  },
  {
    "ref": "@payload-components/stats-proof",
    "name": "stats-proof",
    "title": "Stats Proof",
    "description": "Narrative and prominent string metrics paired with semantic customer proof.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/stats-proof",
    "image": "/registry-previews/f9ad58f97102b75e401012af99f9a120db2f3d6843d100cfe3a64f8f850817c0.png"
  },
  {
    "ref": "@payload-components/stats-grid",
    "name": "stats-grid",
    "title": "Stats Grid",
    "description": "Heading and intro above a responsive grid of large string metrics on rule-topped columns.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/stats-grid",
    "image": "/registry-previews/d9fec9744d7b21043abd0862895e694e86c5c2c91891fe41159e502778b42b83.png"
  },
  {
    "ref": "@payload-components/stats-card",
    "name": "stats-card",
    "title": "Stats Card",
    "description": "A centred heading above one divided panel that splits metrics into equal columns.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/stats-card",
    "image": "/registry-previews/e6555cd6b8608e2c0ad1c183ce25dbe33a8209e0d7e18768705877b53a406319.png"
  },
  {
    "ref": "@payload-components/stats-inline",
    "name": "stats-inline",
    "title": "Stats Inline",
    "description": "Heading and intro above rule-topped rows where each figure reads as one sentence.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/stats-inline",
    "image": "/registry-previews/c54aca443ed9ba357ccd0eaabd366ccb383fe057a858abf32786da1c61212e67.png"
  },
  {
    "ref": "@payload-components/pricing-cards",
    "name": "pricing-cards",
    "title": "Pricing Cards",
    "description": "Three-up pricing table of editable plan cards with a highlighted plan.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/pricing-cards",
    "image": "/registry-previews/93bf98d2bcedadd11d33e8b10f5a6a272f51184ec07d819e63cdd303f5463c17.png"
  },
  {
    "ref": "@payload-components/pricing-cards-muted",
    "name": "pricing-cards-muted",
    "title": "Pricing Cards Muted",
    "description": "Three-up pricing table on muted card surfaces with a highlighted plan.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/pricing-cards-muted",
    "image": "/registry-previews/60b876a3a0205bf57851f30a9f75b7abe65e4a43805c396cac45e4df5450c513.png"
  },
  {
    "ref": "@payload-components/pricing-cards-cta",
    "name": "pricing-cards-cta",
    "title": "Pricing Cards CTA",
    "description": "Three-up pricing table with the CTA inside each plan header.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/pricing-cards-cta",
    "image": "/registry-previews/00af2a602df2987fcbac6e0f02463572d3bf3439aa379453a595323b5676a1d4.png"
  },
  {
    "ref": "@payload-components/pricing-split",
    "name": "pricing-split",
    "title": "Pricing Split",
    "description": "Two-plan split pricing: a compact entry plan beside an expanded featured plan.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/pricing-split",
    "image": "/registry-previews/f131d0babaf190f5619751d5ae3a6c8aed8b43d023dabce1e39f52267e0842bb.png"
  },
  {
    "ref": "@payload-components/pricing-enterprise",
    "name": "pricing-enterprise",
    "title": "Pricing Enterprise",
    "description": "Single wide enterprise pricing panel with an editable trust-logo wall.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/pricing-enterprise",
    "image": "/registry-previews/c8e1f008b63babc2492cc8796f6a97062a2ba87d92330f96992134fb03e4a7b1.png"
  },
  {
    "ref": "@payload-components/collection-query",
    "name": "collection-query",
    "title": "Collection Query",
    "description": "A Pages block that queries the starter Posts collection by category or manual selection and renders grid, list, or featured cards.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/collection-query",
    "image": "/registry-previews/2d2e8a4248f6cb41da8a86ada6328e7c49862b7b814dee5cee63301b04173c47.png"
  },
  {
    "ref": "@payload-components/footer-columns",
    "name": "footer-columns",
    "title": "Footer Columns",
    "description": "A brand block beside labelled columns of navigation links, closed by a copyright rule.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/footer-columns",
    "image": "/registry-previews/534715b5ae5489f0b4fd308dedb84e590c360949f21ae4f0e8f94d2bf5925350.png"
  },
  {
    "ref": "@payload-components/footer-simple",
    "name": "footer-simple",
    "title": "Footer Simple",
    "description": "A compact footer keeping the brand and one wrapped row of links on a line, copyright beneath.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/footer-simple",
    "image": "/registry-previews/e518a0621b93a6d278f31e01fbd01fda29fac5f9da9ea3abcce43f6a40c05ce7.png"
  },
  {
    "ref": "@payload-components/footer-centered",
    "name": "footer-centered",
    "title": "Footer Centered",
    "description": "A centred brand, tagline, and navigation above a rule carrying copyright and policy links.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/footer-centered",
    "image": "/registry-previews/ac104f18b3909655e7e20de93ed9d5f17a7bb2798f3a388c3c534419ff1bebd7.png"
  },
  {
    "ref": "@payload-components/contact-form-basic",
    "name": "contact-form-basic",
    "title": "Contact Form Basic",
    "description": "An accessible contact form with name, email, organization, and message fields, inline validation, and confirmed submission feedback.",
    "kind": "block",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/contact-form-basic",
    "image": "/registry-previews/36e78531f6634bfaa9829687125cdd0928a7c4960fe2cf3a6a5f5e58d43d6c89.png"
  },
  {
    "ref": "@payload-components/post-hero",
    "name": "post-hero",
    "title": "Post Hero",
    "description": "An editorial article header with title, summary, categories, byline, date, and an optional image slot.",
    "kind": "component",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/post-hero",
    "image": "/registry-previews/2cbf6bd3fe0cdef8b39e53eec6ca5ca14cc1682b25f41c816612966f75f60757.png"
  },
  {
    "ref": "@payload-components/author-card",
    "name": "author-card",
    "title": "Author Card",
    "description": "An article author profile with optional avatar, role, biography, and profile link.",
    "kind": "component",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/author-card",
    "image": "/registry-previews/275c4e26458eb27c9e7793a3378adc174004a913779262c4ff47bba68ccb38cc.png"
  },
  {
    "ref": "@payload-components/newsletter-callout",
    "name": "newsletter-callout",
    "title": "Newsletter Callout",
    "description": "A newsletter signup callout with a consumer-owned form endpoint.",
    "kind": "component",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/newsletter-callout",
    "image": "/registry-previews/221ce10a3abf7d161217bf54d54dd3b89004e1bbec2c0da40739f708949624e4.png"
  },
  {
    "ref": "@payload-components/related-posts",
    "name": "related-posts",
    "title": "Related Posts",
    "description": "A compact end-of-post list of related articles your template selects; the current post is always excluded.",
    "kind": "component",
    "source": "@payload-components",
    "previewUrl": "https://www.payload-components.xyz/components/preview/related-posts",
    "image": "/registry-previews/5f151125d9f34bacb38be4c2c84ce62c49ed3a3d27fb3f9836a2381723d9b716.png"
  }
]
